### ISSUE TITLE
Some review comments + needs fixing!

### ISSUE THREAD

**Issue by Apollon77** [instalator/ioBroker.exchangerates#1]
* Please disable or fix appveyor :-)
* you enabled that there is an own "tab" in iopackage ... but I can not find any tab_m.html ?!
* the instance link really goes to vis edit? https://github.com/instalator/ioBroker.exchangerates/blob/master/io-package.json#L86
* interesting approach in https://github.com/instalator/ioBroker.exchangerates/blob/master/main.js#L50 ... but sorry will product trouble. the fact if a state value is defined for an object is no reliable way to find out if the oject exists. AND you use setObjects means: If state db was reset you seimply recreate the object which causes overwriting custom values in js-controller < 2.2 Please change to getObject and not getState!
* interval set in https://github.com/instalator/ioBroker.exchangerates/blob/master/main.js#L314 is not cleared in unload, so breaks compact mode!

Thank you for fast fixing these issues!

**Comment by instalator** [comment]
> * Please disable or fix appveyor :-)

I do not know what it is

**Comment by Apollon77** [comment]
Check the commit view in github ... there is the red cross after each commit, click it. There you see the CI test results from travis (green) and appveyor (red I think because active somehow, but not configured. so click the appveyor link, login with your guthub account there and delete that appveyor project ... I think you had it activated somewhen back in time

**Comment by instalator** [comment]
> Check the commit view in github ... there is the red cross after each commit, click it. There you see the CI test results from travis (green) and appveyor (red I think because active somehow, but not configured. so click the appveyor link, login with your guthub account there and delete that appveyor project ... I think you had it activated somewhen back in time

Please double-check

**Comment by Apollon77** [comment]
Testing green now and ok 👍

Please also remove the

>     "installedFrom": "https://github.com/instalator/ioBroker.exchangerates/tarball/c78c148d8317b3c52ef7946025d97e7630d0fef1"

from io-package!

**Comment by instalator** [comment]
Ok
